# Generated by Django 4.2.17 on 2024-12-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_session_record_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='record_url',
        ),
        migrations.AddField(
            model_name='session',
            name='record_file',
            field=models.FileField(null=True, upload_to='records'),
        ),
    ]
