# Generated by Django 4.2.17 on 2024-12-12 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_remove_session_record_url_session_record_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='converted_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
