# Generated by Django 4.2.17 on 2024-12-12 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_session_converted_text_session_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='converted_text',
            new_name='recording_notes',
        ),
    ]
